apache/sling-slingfeature-maven-plugin

src/main/java/org/apache/sling/feature/maven/ProjectHelper.java

SLING-7985 - ProjectHelper#getConfigValue() puts null values to the resulting Set<String> values

---

src/main/java/org/apache/sling/feature/maven/mojos/AnalyseFeaturesMojo.java

allow the users configure the Analyzer tasks by conventional include/exclude pattern
In that way, users can configure the plugin on that way:
```
<plugin>
<groupId>org.apache.sling</groupId>
<artifactId>slingfeature-maven-plugin</artifactId>
<version>${slingfeature-maven-plugin.version}</version>
<executions>
<execution>
<id>analyze</id>
<phase>validate</phase>
<goals>
<goal>analyse-features</goal>
</goals>
<configuration>
<includeTasks>
<includeTask>api-regions</includeTask>
</includeTasks>
</configuration>
</execution>
[...]
</executions>
</plugin>
```
please, before merging it, https://github.com/apache/sling-org-apache-sling-feature-analyser/pull/5 is required to be applied first!

SLING-7988 - Allow Analyzer include/exclude tasks by id, in order to enable specific Tasks in the Maven plugin

---

src/main/java/org/apache/sling/feature/maven/mojos/ApisJarMojo.java

empty string replaced with a space, which can compromise original source and stumble in 'empty character literal' error

SLING-8273 - APIs jar MOJO doesn't produce Javadoc if sources contain non-ascii chars

---

pom.xml

added required dependencies in order to invoke the new AnalyzerTask

SLING-8251 - Support checking dependencies for content packages

---

src/it/apis-jar-wrapped-flattened-classes/src/main/features/main.json
src/main/java/org/apache/sling/feature/maven/mojos/ApisJarMojo.java

* preventing javadoc jar generation when sources dir is empty
* using a correct Java package existing in bundle javadoc jar in IT

SLING-8682 - preventing javadoc jar generation when sources dir is empty

---

pom.xml
src/main/java/org/apache/sling/feature/maven/mojos/AnalyseFeaturesMojo.java

Include the apis-jar check by default.

SLING-8873 - Validate the sourceId property at build time

---

src/main/java/org/apache/sling/feature/maven/mojos/ApisJarMojo.java

Use strict filtering (one parent) when including resources from deflated bins
and sources, and relaxed filtering (multiple parents) otherwise.

SLING-8906 - Include filters are too wide and can pull in unwanted resources

---

README.md
pom.xml
src/it/include-artifact-including-source-features-folder/invoker.properties
src/it/include-artifact-including-source-features-folder/pom.xml
src/it/include-artifact-including-source-features-folder/src/main/fm/feature-test-repoinit.json
src/it/include-artifact-including-source-features-folder/verify.bsh
src/it/include-artifact-including-source-features/invoker.properties
src/it/include-artifact-including-source-features/pom.xml
src/it/include-artifact-including-source-features/src/main/features/feature-test-repoinit.json
src/it/include-artifact-including-source-features/verify.bsh
src/it/include-artifact-no-classifier/invoker.properties
src/it/include-artifact-no-classifier/pom.xml
src/it/include-artifact-no-classifier/verify.bsh
src/it/include-artifact-simple/invoker.properties
src/it/include-artifact-simple/pom.xml
src/it/include-artifact-simple/verify.bsh
src/it/include-artifact-start-order/invoker.properties
src/it/include-artifact-start-order/pom.xml
src/it/include-artifact-start-order/verify.bsh
src/main/java/org/apache/sling/feature/maven/mojos/IncludeArtifactMojo.java

This is a redo of the PR #41 with a clean set of changes.
Any project that wants to assemble a Project FM by including existing FMs needs a way to install the source FMs from a POM into the local Maven repo first.

Replacement PR for #41 with a clean set of changes

---

src/main/java/org/apache/sling/feature/maven/mojos/AggregateFeaturesMojo.java

The writeToDisk boolean attribute can be set to true on aggregates that are not
attached to have them written to disk during the build process.

SLING-9461 Access Feature Model Aggregates as Files during Maven Build, even if they're not attached

---

src/main/java/org/apache/sling/feature/maven/mojos/AbstractFeatureMojo.java
src/main/java/org/apache/sling/feature/maven/mojos/IncludeArtifactMojo.java

During include-artifact mojo execution the start level for the attached jar/bundle can be set through jarStartOrder.
This was only working for FM files inside the source folder. For created FMs the jar/bundle would not receive the jarStartOrder.
The jarStartOrder param was changed from int to String because otherwise the not null check wouldnt be possible. Without the not null check the start order would be added always.

Fixes bug: jarStartOrder can only be set for FMs in the source folder.

---

src/main/java/org/apache/sling/feature/maven/Substitution.java
src/test/java/org/apache/sling/feature/maven/SubstitutionTest.java

Substitutions for the "replacePropertyVariables" values should prefer the system property value (if available) over the project property value.  
For example, the use case of a parameterized jenkins job where the users choice should be passed along to maven and used to configure/prepare the environment to run a set of tests against.

SLING-10060 Substitutions for the "replacePropertyVariables" values should prefer the system property value

---

src/main/java/org/apache/sling/feature/maven/mojos/AbstractFeatureMojo.java

After switching to the 1.4.22 release version of the plugin, I noticed that the change for SLING-10035 appears to be creating a set of empty folders in the wrong place in my linux environment.
Using a debugger, I see that the targetDir File object is constructed at AbstractFeatureMojo line 244 with the "child" second argument already resolved to be an absolute path.  This appears to append the absolute child path to the parent path rather than checking if "child" is relative or absolute to resolve it.
Expect the targetDir resolution to properly resolve the path when the child is an absolute path.

SLING-10069 The generated features target dir is created in the wrong place

---

pom.xml

With the release of repoinit parser 1.7.0 and repoinit jcr implementation 1.1.40 update the downstream dependencies to make the fix for [SLING-10740](https://issues.apache.org/jira/browse/SLING-10740) available.

SLING-11389 Update repoinit parser dependency to latest

---

src/test/java/org/apache/sling/feature/maven/mojos/JarDecompressorTest.java

Don't run the problematic test on Windows

SLING-11935 - JarDecompressorTest.testWithEmbeddedJar fails on Jenkins/Windows

---

pom.xml

This adds relevant javadoc links to the generated site for complex parameter types.

Use Maven Plugin Tools 3.9.0

---

.gitattributes
src/test/java/org/apache/sling/feature/maven/mojos/JarDecompressorTest.java

Always keep *nix line endings for textfile.txt

SLING-11935 fix JarDecompressorTest on Windows

---

pom.xml

- update o.a.s.feature.analyzer to 2.0.0 due to its
transitive dependency to o.a.s.repoinit.parser

SLING-12127 - Update o.a.s.repoinit.parser to 1.9.0 in slingfeature-maven-plugin

---

pom.xml

Update to a more recent version of the invoker-maven-plugin, which depends on a version of Groovy with Java 21 support.

SLING-12305 - Build fails on Java 21 due to invoker plug-in: Unsupported class file major version 65

---

pom.xml

Switch to using the Sling Commons Johnzon implementation for JSON parsing, as it avoids using the ServiceLoader. This should avoid classloading headaches in OSGI environments and have no practical impact in Maven builds.

SLING-12173 - Configuration errors in Eclipse for projects using the slingfeature-maven-plugin

---

src/main/java/org/apache/sling/feature/maven/mojos/AbstractFeatureMojo.java
src/main/java/org/apache/sling/feature/maven/mojos/AggregateFeaturesMojo.java
src/main/java/org/apache/sling/feature/maven/mojos/AnalyseFeaturesMojo.java

* If multiple scans have been configured, only the results of the last execution have been considered for the final result calculation
* Tested locally
* Before: validation passed
* After:
```
[ERROR] Analyser detected errors on feature '**'.
[ERROR] [content-packages-installables] **: Content ** is not resolved and can not be checked.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.335 s
[INFO] Finished at: 2024-08-01T17:35:20+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.sling:slingfeature-maven-plugin:1.8.5-SNAPSHOT:analyse-features (analyze) on project …
```

Improve Error Handling

---

src/test/java/org/apache/sling/feature/maven/mojos/JarDecompressorTest.java

Disable problematic test on Windows

SLING-12596 - JarDecompressorTest.testWithEmbeddedJar fails on Jenkins/Windows after upgrading to Parent 62
